### DISCUSSION TITLE
MySQL和Redis的Chart包不存在。

### DISCUSSION THREAD

**Discussion by joker-bai** [hhyo/Archery#2078] [Q&A]
![image](https://user-images.githubusercontent.com/34888500/224889075-c75d00b8-8933-44fd-93b0-d7903f5b0451.png)

**Comment by LeoQuote** [comment]
请查看最新的 wiki, 谢谢

**Reply by joker-bai** [reply]
![image](https://user-images.githubusercontent.com/34888500/224907871-846500f1-553a-4ddb-bc3c-13dda02deb77.png)
又出现新的问题，MySQL 安装过程中直接crash

**Reply by LeoQuote** [reply]
请详细描述你做了什么, 你期待什么, 报了什么错, 你提供的这个截图价值不大, 没有任何有用的日志

**Reply by joker-bai** [reply]
1、具体的操作
```
# 添加仓库
helm repo add douban https://douban.github.io/charts/
helm repo update

# 下载包
helm pull douban/archery

# 修改value.yaml配置
redis:
    master:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "local"
mysql:
      persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 50Gi
      storageClass: "local"

# 部署应用
helm install archery -n devops .

# 应用清单
![image](https://user-images.githubusercontent.com/34888500/224910127-d0115566-1770-4d29-8a36-368eef31175b.png)

```

然后发现mysql启动不起来，describe和logs日志如下：
![image](https://user-images.githubusercontent.com/34888500/224910318-894eb8fc-d9fc-44fb-b149-bffb5f2e9379.png)

> PS：只有这些日志

2、期望的效果是成功部署archery
