### DISCUSSION TITLE
Archery 如何进行多实例部署保证生产高可用呢

### DISCUSSION THREAD

**Discussion by magicxiexiaodong** [hhyo/Archery#2419] [Q&A]
我按照官网文档可以进行docker-compose.yml进行部署，但是存在单点故障问题，请问一下如何进行生产的多实例部署

**Comment by LeoQuote** [comment]
archery 的网页本身是可以部署多个实例, 后端的 django-q 也可以部署多个实例, 你可以从这两个方向出发探索高可用的部署方式, 欢迎贡献文档.

**Reply by magicxiexiaodong** [reply]
我在提供的 docker-compose.yml里面
```
`version: '3'

services:
  redis:
    image: redis:5
    container_name: redis
    restart: always
    command: redis-server --requirepass 123456
    expose:
      - "6379"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/datadir:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: archery
      MYSQL_ROOT_PASSWORD: 123456

  goinception:
    image: hanchuanchuan/goinception
    container_name: goinception
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - "./inception/config.toml:/etc/config.toml"

  archery1:  # 第一个 Archery 服务实例
    image: hhyo/archery:v1.9.1
    container_name: archery1
    restart: always
    ports:
      - "9123:9123"
    volumes:
      - "./archery/settings.py:/opt/archery/local_settings.py"
      - "./archery/soar.yaml:/etc/soar.yaml"
      - "./archery/docs.md:/opt/archery/docs/docs.md"
      - "./archery/downloads:/opt/archery/downloads"
      - "./archery/sql/migrations:/opt/archery/sql/migrations"
      - "./archery/logs:/opt/archery/logs"
      - "./archery/keys:/opt/archery/keys"
    entrypoint: "dockerize -wait tcp://mysql:3306 -wait tcp://redis:6379 -timeout 60s /opt/archery/src/docker/startup.sh"
    env_file:
      - .env
  archery2:  # 第二个 Archery 服务实例
    image: hhyo/archery:v1.9.1
    container_name: archery2
    restart: always
    ports:
      - "9124:9123"  # 使用不同的本地端口
    volumes:
      - "./archery/settings.py:/opt/archery/local_settings.py"
      - "./archery/soar.yaml:/etc/soar.yaml"
      - "./archery/docs.md:/opt/archery/docs/docs.md"
      - "./archery/downloads:/opt/archery/downloads"
      - "./archery/sql/migrations:/opt/archery/sql/migrations"
      - "./archery/logs:/opt/archery/logs"
      - "./archery/keys:/opt/archery/keys"
    entrypoint: "dockerize -wait tcp://mysql:3306 -wait tcp://redis:6379 -timeout 60s /opt/archery/src/docker/startup.sh"
    env_file:
      - .env`
```

给定义了两个archery 然后在archery1里面去执行了

```
#表结构初始化
docker exec -ti archery /bin/bash
cd /opt/archery
source /opt/venv4archery/bin/activate
python3 manage.py makemigrations sql
python3 manage.py migrate

#数据初始化
python3 manage.py dbshell<sql/fixtures/auth_group.sql
python3 manage.py dbshell<src/init_sql/mysql_slow_query_review.sql

#创建管理用户
python3 manage.py createsuperuser

#重启服务
docker restart archery1
docker restart archery2
#日志查看和问题排查
docker logs archery -f --tail=10
``` 
并且注册了一个xxd的管理员账号，在archery1 9123 是已经登录且能正常访问，网页能打开localhost:9124 但是去登录xxd账号的时候，却给我 报  CSRF验证失败的错误，我查看相关资料 请问下这个是不是跟 SECRET_KEY 有关系？按理讲archery1和archery2都用的同样的 mysql 和 redis 就能部署高可用了
