### ISSUE TITLE
[ SQL上线 ]

### ISSUE THREAD

**Issue by cai823294620** [hhyo/Archery#160]
进行SQL上线时出现如下报错：
![image](https://user-images.githubusercontent.com/44595276/57064327-86c11200-6cf8-11e9-824e-51548227a4bc.png)

所使用的数据库是其他主机的数据库。不是docker-compose的默认库

**Comment by LeoQuote** [comment]
具体修改了哪些配置，请列举出来。

**Comment by cai823294620** [comment]
#### docker-compose的配置如下，仅注释了Mysql
```
version: '3'

services:
  redis:
    image: redis:5
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

#  mysql:
#    image: mysql:5.7
#    container_name: mysql
#    restart: always
#    ports:
#      - "3306:3306"
#    volumes:
#      - "./mysql/my.cnf:/etc/mysql/my.cnf"
#      - "./mysql/datadir:/var/lib/mysql"
#    environment:
#      MYSQL_DATABASE: archery
#      MYSQL_ROOT_PASSWORD: 123456

  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    volumes:
      - "./mongo/datadir:/data/db"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  inception:
    image: hhyo/inception
    container_name: inception
    restart: always
    ports:
      - "6669:6669"
    volumes:
      - "./inception/inc.cnf:/etc/inc.cnf"

  goinception:
    image: hanchuanchuan/goinception
    container_name: goinception
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - "./inception/config.toml:/etc/config.toml"

  archery:
    image: hhyo/archery
    container_name: archery
    restart: always
    ports:
      - "9123:9123"
    volumes:
      - "./archery/settings.py:/opt/archery/archery/settings.py"
      - "./archery/soar.yaml:/etc/soar.yaml"
      - "./archery/downloads:/opt/archery/downloads"
    command: ["bash","/opt/archery/src/docker/startup.sh"]
    environment:
      NGINX_PORT: 9123
```
#### 然后进入archery容器，修改Mysql的配置。
vi /opt/archery/archery/settings.py
```
   119	DATABASES = {
   120	    'default': {
   121	        'ENGINE': 'django.db.backends.mysql',
   122	        'NAME': 'archery',
   123	        'USER': 'root',
   124	        'PASSWORD': '123456',
   125	        'HOST': '192.168.10.187',
   126	        'PORT': '3316',
   127	        'OPTIONS': {
   128	            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
   129	            'charset': 'utf8mb4'
   130	        },
   131	        'TEST': {
   132	            'NAME': 'test_archery',
   133	            'CHARSET': 'utf8',
   134	        },
```
