### ISSUE TITLE
archery 用kubernetes 部署，出现错误

### ISSUE THREAD

**Issue by zhouying370481** [hhyo/Archery#52]
archery-deployment.yaml ：
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: archery
  name: archery
  namespace: archery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archery
  template:
    metadata:
      labels:
        app: archery
    spec:
      containers:
      - args:
        - -c
        - /opt/archery/src/docker/startup.sh
        command:
        - bash
        image: hhyo/archery
        imagePullPolicy: Always
        name: archery
        ports:
        - containerPort: 9123
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/archery/archery/
          name: archery-settings
        - mountPath: /opt/archery/archery/settings.py
          name: setting
          readOnly: true
          subPath: settings.py
        - mountPath: /opt/archery/downloads
          name: archery-downloads
        - mountPath: /etc/soar.yaml
          name: soar
          readOnly: true
          subPath: soar.yaml
      volumes:
      - hostPath:
          path: /opt/archery/archery/
          type: ""
        name: archery-settings
      - configMap:
          name: setting
        name: setting
      - name: archery-downloads
        persistentVolumeClaim:
          claimName: archery-pv-claim
      - configMap:
          name: soar
        name: soar
```
_________________________________________________________________________________________

kubectl apply -f archery-deployment.yaml 
出现错误：
```
[root@test01 mongodb]# kubectl     log   archery-5d5ddfffb4-jkdhj -n archery 
log is DEPRECATED and will be removed in a future version. Use logs instead.
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
    self.spawn_workers()
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 612, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv4archery/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/opt/venv4archery/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```
请问如何解决。谢谢。

**Comment by hhyo** [comment]
在启动脚本内加上--log-level=debug看下具体日志，你提供的yaml文件缺少volums信息，我本地也无法重现

**Comment by zhouying370481** [comment]
> 在启动脚本内加上--log-level=debug看下具体日志，你提供的yaml文件缺少volums信息，我本地也无法重现

你好，感谢你的回复。我现在pods 运行了。但是错误有出现了：
当我进入容器运行：
```
source /opt/venv4archery/bin/activate
python3 manage.py makemigrations sql  #这一步如果遇到报错可忽略```
这一步出现错了，报错许下:
```
 python3 manage.py makemigrations sql
/opt/venv4archery/lib/python3.6/site-packages/wtforms/ext/sqlalchemy/__init__.py:9: DeprecationWarning: wtforms.ext.sqlalchemy is deprecated, and will be removed in WTForms 3.0. The package has been extracted to a separate package wtforms_sqlalchemy: https://github.com/wtforms/wtforms-sqlalchemy .
Or alternately, check out the WTForms-Alchemy package which provides declarative mapping and more: https://github.com/kvesteri/wtforms-alchemy
  DeprecationWarning
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
    return checks.run_checks(**kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/checks/model_checks.py", line 27, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 1200, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/base.py", line 1272, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 894, in check
    errors = super().check(**kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 206, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 303, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/validation.py", line 21, in check_field
    field_type = field.db_type(self.connection)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 648, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 133, in data_types
    if self.features.supports_microsecond_precision:
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/features.py", line 65, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 349, in mysql_version
    match = server_version_re.match(self.mysql_server_info)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 343, in mysql_server_info
    with self.temporary_connection() as cursor:
  File "/usr/local/python3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 576, in temporary_connection
    cursor = self.cursor()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' (110)")
```
接着执行：
```
python3 manage.py migrate
```
报错：
```
 python3 manage.py migrate




Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' (110)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 57, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' (110)")
```
一开始我看是mysql 里只有root 用户，没有archery用户，于是，我建立了archery 用户，并设置了密码：123456 ，重新执行脚本，发现还是错误。
谢谢~

**Comment by hhyo** [comment]
`_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' (110)")`表示应用无法连接配置的mysql，所以还没有到用户验证那一步
可以在容器内使用命令连接`mysql -h  -P -u -p `，确认是否可以正常访问mysql服务，其他服务也是一样
表结构初始化后成功后需要重启容器

**Comment by zhouying370481** [comment]
> `_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' (110)")`表示应用无法连接配置的mysql，所以还没有到用户验证那一步
> 可以在容器内使用命令连接`mysql -h -P -u -p `，确认是否可以正常访问mysql服务，其他服务也是一样
> 表结构初始化后成功后需要重启容器

在archery pod 里，mysql -uroot -p -h:  如果我指定mysqlpod ip的时候是可以连接进去的。但是我mysql-pod 做了service ，名字是：mysql. 当我执行：mysql -uroot -p -hmysql 的时候，就不能执行了。
一开始我是没有做service 的，但是执行你的脚本，报错。所以，我不确定你archery 里是配置通过什么方式去连接mysql 的。名字是mysql 吗？

**Comment by zhouying370481** [comment]
archery 去和mysql 去通信，连接不上mysql ，连接方式是用的别名吗？n那么别名在哪里找或者查看？

**Comment by hhyo** [comment]
配置文件内可修改，见：[配置文件](https://github.com/hhyo/archery/blob/master/archery/settings.py#L111)
包括mysql、redis、mongodb

**Comment by zhouying370481** [comment]
> 配置文件内可修改，见：[配置文件](https://github.com/hhyo/archery/blob/master/archery/settings.py#L111)
> 包括mysql、redis、mongodb

谢谢，。已经搞定了，是我service 没做好，谢谢！

**Comment by tianyang010** [comment]
请问下您那边修改了什么配置，我这边也报跟您相同的错误 @Ezuka

**Comment by LeoQuote** [comment]
感谢您的尝试，如果方便的话可以提一个pr，把k8s的yaml文件分享一下，谢谢。

（没注意看这是个两个月前的issue了

**Comment by zhouying370481** [comment]
> 请问下您那边修改了什么配置，我这边也报跟您相同的错误 @Ezuka

```
archery 默认查询是从从库进行，执行sql 操作在主库上执行。并且不能执行
drop database 等删库操作。
注册用户的时候必须要填写中文名称，不然，sql 执行的时候会报错。
注册完用户的时候。需要关联组：
系统管理--> 资源组管理-->添加组
系统管理--> 资源组管理-->添加组，点击添加的组，管理，点击新增关联对象，
选择用户和实例。关联完毕以后，就可以执行操作和查询了。
```

**Comment by zhouying370481** [comment]
fyi 

# Archery-server:

1,创建namespace ,便于资源隔离。

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: archery
  name: archery
```
```
应用： kubectl apply -f namespace.yaml
```
2,创建  相关pv。

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archery-pv-claim
  namespace: archery
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  namespace: archery
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: archery
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```
```
应用：kubectl apply -f pv.yaml
```
3,创建mysql mongo secret 。

```
apiVersion: v1
kind: List
  metadata:
    namespace: archery
items:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata: 
     name: mysql-secret
     namespace: archery
  data:
    mongodb-pass: "MTIzNDU2"
    mongodb-user: "cm9vdA=="
    mysql-db: "YXJjaGVyeQ=="
    mysql-root-pass: "MTIzNDU2"
```
4,创建mysql deployment ,service

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archery
    tier: db
  name: mysql
  namespace: archery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archery
      tier: db
  template:
    metadata:
      labels:
        app: archery
        name: mysql
        tier: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: mysql-db
              name: mysql-secret
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-pass
              name: mysql-secret
        image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqld-persistent-storage
        - mountPath: /etc/mysql/my.cnf
          name: mysqld-config
          readOnly: true
          subPath: my.cnf
      volumes:
      - name: mysqld-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysqld-config
        configMap:
          name: mysqld-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: archery
    tier: db
  namespace: archery
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  clusterIP: None
  selector:
    name: mysql
```
```
应用： kubectl apply -f  mysql-deployment.yaml
```
5,创建mongo deployment ,service

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archery
    tier: db
  name: mongodb-server
  namespace: archery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archery
      tier: db
  template:
    metadata:
      labels:
        app: archery
        name: mongodb-server
        tier: db
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongodb-user
              name: mysql-secret
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-pass
              name: mysql-secret
        image: mongo:3.6
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-persistent-storage
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
```
```
应用： kubectl apply -f mongodb-deployment.yaml
```
6,创建archery deployment,service.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archery
  name: archery
  namespace: archery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archery
  template:
    metadata:
      labels:
        app: archery
        name: archery
    spec:
      containers:
      - command: [bash]
        args: [-c,/opt/archery/src/docker/startup.sh,'--log-level=debug']
        image: hhyo/archery
        imagePullPolicy: Always
        name: archery
        env:
        - name: NGINX_PORT
          value: "9123"
        ports:
        - containerPort: 9123
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/archery/archery/settings.py
          name: setting
          readOnly: false
          subPath: settings.py
        - mountPath: /opt/archery/downloads
          name: archery-downloads
        - mountPath: /etc/soar.yaml
          name: soar
          readOnly: true
          subPath: soar.yaml
      volumes:
      - name: setting
        configMap:
          name: setting
      - name: archery-downloads
        persistentVolumeClaim:
          claimName: archery-pv-claim
      - name: soar
        configMap:
          name: soar
---
apiVersion: v1
kind: Service
metadata:
  name: archery
  labels:
    app: archery
  namespace: archery
spec:
  type: NodePort
  ports:
  - port: 9123
    targetPort: 9123
    nodePort: 30103
    name: web-http
  selector:
    name: archery
```
```
应用： kubectl apply -f archery-deployment.yaml
```
7,创建inception deployment，service 。

```

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inception
  name: inception
  namespace: archery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inception
  template:
    metadata:
      labels:
        app: inception
    spec:
      containers:
      - image: hhyo/inception
        imagePullPolicy: Always
        name: inception
        ports:
        - containerPort: 6669
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/inc.cnf
          name: inception-conf
          readOnly: true
          subPath: inc.cnf
      volumes:
        - name: inception-conf
          configMap:
            name: inception-conf
```
```
应用： kubectl apply -f inception-deployment.yaml
```
8,创建redis deployment.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: archery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:5
        name: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: archery
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
  clusterIP: None
```
```
应用： kubectl apply -f redis-deployment.yaml
```
```
另外：archery，msql,inception 需要映射配置文件，所以做成configMap
```
```
创建configMap:
```
```
kubectl create configMap  inception-conf --from-file=inc.cnf -n archery
kubectl create configMap   soar  --from-file=soar.yaml -n archery 
kubectl create configMap  mysqld-config --from-file=my.cnf -n archery 
kubectl create configMap  setting --from-file=settings.py -n archery
```
部署成功后，需要登录archery 容器内执行：

```
cd /opt/archery
source /opt/venv4archery/bin/activate
python3 manage.py makemigrations sql  
python3 manage.py migrate#创建管理用户
python3 manage.py createsuperuser

#日志查看和问题排查
docker logs archery
/downloads/log/archery.log
```
# 登录控制台查看：

```
url: http://192.168.200.211:30103
user:Ezuka
passwd:ax_home123
```
# 错误排查

```
archery 默认查询是从从库进行，执行sql 操作在主库上执行。并且不能执行
drop database 等删库操作。
```
```
注册用户的时候必须要填写中文名称，不然，sql 执行的时候会报错。
```
```
注册完用户的时候。需要关联组：
系统管理--> 资源组管理-->添加组
```
添加完组后，需要关联实例和用户

```
系统管理--> 资源组管理-->添加组，点击添加的组，管理，点击新增关联对象，
选择用户和实例。关联完毕以后，就可以执行操作和查询了。
```
# 另外：

```
数据库和表名不支持"-"，需要用"_"，
```
```
其他操作，可以参考官方文档。
```
